query FindUser($uid: ID!) {
  findUserByUID(uid: $uid) {
    _id
    uid
    displayName
    email
    phoneNumber
    photoURL
    accType
    children {
      name
      age
      previousEducation {
        subject
        juzMemorized
        readingLevel
        tajweedLevel
      }
    }
    previousEducation {
      subject
      juzMemorized
      readingLevel
      tajweedLevel
    }
    teacherEducation {
      institutions
      preferredTeachingSubject
      certifications {
        name
        description
      }
      references
      yearsOfExperience
    }
    preferredInstructionMode {
      instructionMode
      remote {
        preferredSchedule {
          Monday {
            start
            end
          }
          Tuesday {
            start
            end
          }
          Wednesday {
            start
            end
          }
          Thursday {
            start
            end
          }
          Friday {
            start
            end
          }
          Saturday {
            start
            end
          }
          Sunday {
            start
            end
          }
        }
      }
      inPerson {
        preferredSchedule {
          Monday {
            start
            end
          }
          Tuesday {
            start
            end
          }
          Wednesday {
            start
            end
          }
          Thursday {
            start
            end
          }
          Friday {
            start
            end
          }
          Saturday {
            start
            end
          }
          Sunday {
            start
            end
          }
        }
        preferredLocation
        maxTravelDistance
      }
    }
  }
}
